name: Feature request
description: Suggest an improvement to Plan Measure
labels:
  - enhancement

body:
  - type: textarea
    id: description
    attributes:
      label: Describe the feature
      description: Explain what you would like to add or improve.
    validations:
      required: true
